resources:
- deployment.yaml
- namespace.yaml
- service.yaml
- ingress.yaml
- secret.yaml
namespace: <namespace>
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: <image-path>
  newTag: <image-tag>
