---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: <tls-name>
  namespace: <namespace>
spec:
  name: <tls-name>
  keysMap:
    ca.crt:
      path: secrets/data/<community>/<service-name>
      key: server.crt
    tls.crt:
      path: secrets/data/<community>/<service-name>
      key: server.crt
    tls.key:
      path: secrets/data/<community>/<service-name>
      key: server.key

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: <secret-name>
  namespace: <namespace>
spec:
  name: <secret-name>
  keysMap:
    <value1>:
      path: secrets/data/<community>/<service-name>
      key: <value1>

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: <secret-name2>
  namespace: <namespace>
spec:
  name: <secret-name2>
  keysMap:
    <value2>:
      path: secrets/data/<community>/<service-name>
      key: <value2>