---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: <my-sa>            # serviceaccount name
  namespace: <namespace>   # the namespace which you defined

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: <my-role>          # role name
  namespace: <namespace>   # the namespace which you defined
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - exec
  - create
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/portforward
  verbs:
  - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: <myrolebinding>
  namespace: <namespace>   # the namespace which you defined
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: <my-role>          # role name
subjects:
- kind: ServiceAccount
  name: <my-sa>            # serviceaccount name
  namespace: <namespace>   # the namespace which you defined
